# Homework 4: Pandas

This notebook has two parts. **Part I** introduces the core pandas concepts you'll need, with short exercises to practice each one. **Part II** applies those skills to a real-world dataset of financial crises spanning 70+ countries and two centuries.

Work through Part I first — the exercises are quick and designed to build muscle memory. By the time you reach Part II, the patterns will feel familiar.

---
# Part I: Introduction to Pandas

## 1. What Is a DataFrame?

A DataFrame is essentially a spreadsheet inside Python. It has rows and columns, just like an Excel sheet, but you can manipulate it with code instead of clicking around.

Let's start by importing pandas and building a tiny dataset by hand.

In [6]:
import pandas as pd

# A DataFrame can be created from a dictionary.
# Each key becomes a column name; each value is a list of entries.

data = {
    "country": ["Brazil", "Germany", "Japan", "Nigeria", "United States"],
    "population_millions": [214, 84, 125, 223, 333],
    "gdp_trillions_usd": [1.92, 4.26, 4.23, 0.44, 25.46],
    "region": ["South America", "Europe", "Asia", "Africa", "North America"]
}

df = pd.DataFrame(data)
df

         country  population_millions  gdp_trillions_usd         region
0         Brazil                  214               1.92  South America
1        Germany                   84               4.26         Europe
2          Japan                  125               4.23           Asia
3        Nigeria                  223               0.44         Africa
4  United States                  333              25.46  North America

That's it — five rows, four columns. The numbers on the left (0, 1, 2, ...) are the **index**. Pandas adds this automatically to give every row a label.

Take a moment to notice the structure: each *row* is a country, and each *column* is a variable we know about that country. This "one row per observation, one column per variable" pattern is the foundation of tidy data, and it's how you'll want to organize most datasets.

### Exercise 1

Create a DataFrame called `un_members` with data for four countries of your choice. It should have three columns: `"country"`, `"year_joined_un"`, and `"continent"`. Display the result.

In [7]:
# Your code here
# Am I supposed to be hardcoding in values or could I leverage the dataframe given to me?
data = {
    "country": ["Brazil", "Germany", "Japan", "Nigeria", "United States"],
    "year_joined_un": [1945, 1973, 1956, 1960, 1945],
    "continent": ["South America", "Europe", "Asia", "Africa", "North America"]
}

df2 = pd.DataFrame(data)

---
## 2. Getting Your Bearings: Inspecting a DataFrame

Before you do anything with data, you need to understand what you're looking at. Pandas gives you a handful of methods for this. These are the ones you'll use constantly.

In [8]:
# .shape tells you (rows, columns)
df.shape

(5, 4)

In [9]:
# .columns lists all column names
df.columns

Index(['country', 'population_millions', 'gdp_trillions_usd', 'region'], dtype='str')

In [10]:
# .dtypes shows the data type of each column
# 'object' usually means text/string; 'int64' and 'float64' are numbers
df.dtypes

country                    str
population_millions      int64
gdp_trillions_usd      float64
region                     str
dtype: object

In [11]:
# .head(n) shows the first n rows (default 5)
# .tail(n) shows the last n rows
# These are essential when your dataset has thousands of rows
# and you just want a quick peek.

df.head(3)

   country  population_millions  gdp_trillions_usd         region
0   Brazil                  214               1.92  South America
1  Germany                   84               4.26         Europe
2    Japan                  125               4.23           Asia

In [12]:
# .describe() gives summary statistics for numeric columns
df.describe()

       population_millions  gdp_trillions_usd
count             5.000000           5.000000
mean            195.800000           7.262000
std              96.704188          10.301079
min              84.000000           0.440000
25%             125.000000           1.920000
50%             214.000000           4.230000
75%             223.000000           4.260000
max             333.000000          25.460000

**Habit to build:** Every time you load a new dataset, run `.shape`, `.columns`, `.dtypes`, and `.head()` before doing anything else. It takes ten seconds and saves you from misunderstandings later.

### Exercise 2

Run `.shape`, `.dtypes`, and `.describe()` on your `un_members` DataFrame from Exercise 1. Based on the output of `.dtypes`, which columns are numeric and which are text? Answer in a comment.

In [13]:
# Your code here
df2.shape

(5, 3)

In [14]:
df2.dtypes
#based on this, country and continent are text, while year_joined is an integer.

country             str
year_joined_un    int64
continent           str
dtype: object

In [15]:
df2.describe()

       year_joined_un
count        5.000000
mean      1955.800000
std         11.691878
min       1945.000000
25%       1945.000000
50%       1956.000000
75%       1960.000000
max       1973.000000

---
## 3. Selecting Data

### Selecting columns

You can grab a single column with bracket notation. This returns a **Series** — pandas' term for a single column of data.

In [16]:
# Single column → returns a Series
df["country"]

0           Brazil
1          Germany
2            Japan
3          Nigeria
4    United States
Name: country, dtype: str

In [17]:
# Multiple columns → pass a list of column names → returns a DataFrame
df[["country", "gdp_trillions_usd"]]

         country  gdp_trillions_usd
0         Brazil               1.92
1        Germany               4.26
2          Japan               4.23
3        Nigeria               0.44
4  United States              25.46

Notice the double brackets `[[ ]]` when selecting multiple columns. The outer brackets are the pandas selection operator; the inner brackets define a Python list.

### Selecting rows

You can select rows by position (like list indexing) using `.iloc`, or by index label using `.loc`.

In [18]:
# .iloc uses integer positions (0-based), just like a Python list
df.iloc[0]       # first row

country                       Brazil
population_millions              214
gdp_trillions_usd               1.92
region                 South America
Name: 0, dtype: object

In [19]:
df.iloc[1:3]     # rows at positions 1 and 2 (the end is exclusive, like slicing)

   country  population_millions  gdp_trillions_usd  region
1  Germany                   84               4.26  Europe
2    Japan                  125               4.23    Asia

In [20]:
# .loc uses the index labels. Since our index is 0, 1, 2, ...
# it looks the same here, but .loc is inclusive on both ends.
df.loc[1:3]      # rows with index labels 1, 2, AND 3

   country  population_millions  gdp_trillions_usd  region
1  Germany                   84               4.26  Europe
2    Japan                  125               4.23    Asia
3  Nigeria                  223               0.44  Africa

The `.iloc` vs `.loc` distinction trips everyone up at first. The short version: use `.iloc` when you're thinking in terms of position ("give me the first three rows"), and `.loc` when you're thinking in terms of labels.

### Exercise 3

Using the `df` DataFrame:

a) Select just the `"country"` and `"region"` columns and display them.

b) Use `.iloc` to select the last two rows.

c) Run both `.loc[1:3]` and `.iloc[1:3]`. How many rows does each return? Explain the difference in a comment.

In [21]:
# 3a: Your code here
df.loc[:,["country","region"]]

         country         region
0         Brazil  South America
1        Germany         Europe
2          Japan           Asia
3        Nigeria         Africa
4  United States  North America

In [22]:
# 3b: Your code here
df.iloc[-2:]

         country  population_millions  gdp_trillions_usd         region
3        Nigeria                  223               0.44         Africa
4  United States                  333              25.46  North America

In [23]:
# 3c: Your code here — run both and explain the difference in a comment
df.iloc[1:3]

   country  population_millions  gdp_trillions_usd  region
1  Germany                   84               4.26  Europe
2    Japan                  125               4.23    Asia

In [24]:
df.loc[1:3]
# The difference is that .iloc is exclusive on the end index, while .loc is inclusive. So .iloc[1:3] gives rows at positions 1 and 2, while .loc[1:3] gives rows with index labels 1, 2, and 3.

   country  population_millions  gdp_trillions_usd  region
1  Germany                   84               4.26  Europe
2    Japan                  125               4.23    Asia
3  Nigeria                  223               0.44  Africa

---
## 4. Filtering Rows

This is where pandas starts to feel powerful. You can filter a DataFrame by writing a condition, and pandas returns only the rows where that condition is `True`.

Let's say we want countries with GDP above $4 trillion.

In [25]:
# Step 1: The condition itself produces a Series of True/False values
df["gdp_trillions_usd"] > 4

0    False
1     True
2     True
3    False
4     True
Name: gdp_trillions_usd, dtype: bool

In [26]:
# Step 2: Pass that True/False series back into the DataFrame
# Pandas keeps only the rows where the value is True

high_gdp = df[df["gdp_trillions_usd"] > 4]
high_gdp

         country  population_millions  gdp_trillions_usd         region
1        Germany                   84               4.26         Europe
2          Japan                  125               4.23           Asia
4  United States                  333              25.46  North America

You can combine conditions with `&` (and) and `|` (or). Each condition needs its own parentheses.

In [27]:
# Countries with GDP > 4 trillion AND population > 100 million
df[(df["gdp_trillions_usd"] > 4) & (df["population_millions"] > 100)]

         country  population_millions  gdp_trillions_usd         region
2          Japan                  125               4.23           Asia
4  United States                  333              25.46  North America

### Exercise 4

Using the `df` DataFrame:

a) Filter for countries with a population over 200 million. How many are there?

b) Filter for countries that are in either `"Asia"` or `"Europe"`. (Hint: use `|` for "or".)

In [28]:
# 4a: Your code here
df["population_millions"] > 200

0     True
1    False
2    False
3     True
4     True
Name: population_millions, dtype: bool

In [29]:
# 4b: Your code here
df[(df["region"] == "Asia") | (df["region"] == "Europe")]

   country  population_millions  gdp_trillions_usd  region
1  Germany                   84               4.26  Europe
2    Japan                  125               4.23    Asia

---
## 5. Adding and Modifying Columns

You can create new columns from existing ones, just like adding a formula column in a spreadsheet.

In [30]:
# GDP per capita (in USD)
# GDP is in trillions, population is in millions,
# so (trillions / millions) = millions → multiply by 1e6 to get USD

df["gdp_per_capita"] = (df["gdp_trillions_usd"] / df["population_millions"]) * 1e6
df

,country,population_millions,gdp_trillions_usd,region,gdp_per_capita
0,Brazil,214,1.92,South America,8971.962617
1,Germany,84,4.26,Europe,50714.285714
2,Japan,125,4.23,Asia,33840.000000
3,Nigeria,223,0.44,Africa,1973.094170
4,United States,333,25.46,North America,76456.456456

Notice how the arithmetic operated on every row at once — no `for` loop needed. This is one of pandas' key advantages: **vectorized operations** let you work on entire columns in a single expression.

### Exercise 5

Add a new column to `df` called `"gdp_per_capita_thousands"` that expresses GDP per capita in thousands of USD (divide `gdp_per_capita` by 1000). Display the result.

In [31]:
df.head()

,country,population_millions,gdp_trillions_usd,region,gdp_per_capita
0,Brazil,214,1.92,South America,8971.962617
1,Germany,84,4.26,Europe,50714.285714
2,Japan,125,4.23,Asia,33840.000000
3,Nigeria,223,0.44,Africa,1973.094170
4,United States,333,25.46,North America,76456.456456

In [32]:
# Your code here
df["gdp_per_capita_thousands"] = df["gdp_trillions_usd"] / 1000000000
#bruh you gave me the wrong key name for gdp per capita
#oh nevermind, i forgot to run a cell before this

---
## 6. Sorting

`.sort_values()` reorders rows. This is useful for ranking — which country has the highest GDP per capita?

In [33]:
df.sort_values("gdp_per_capita", ascending=False)

,country,population_millions,gdp_trillions_usd,region,gdp_per_capita,gdp_per_capita_thousands
4,United States,333,25.46,North America,76456.456456,2.546000e-08
1,Germany,84,4.26,Europe,50714.285714,4.260000e-09
2,Japan,125,4.23,Asia,33840.000000,4.230000e-09
0,Brazil,214,1.92,South America,8971.962617,1.920000e-09
3,Nigeria,223,0.44,Africa,1973.094170,4.400000e-10

### Exercise 6

Sort `df` by `"population_millions"` in ascending order (smallest to largest). Which country has the smallest population in our dataset?

In [34]:
# Your code here
df.sort_values("population_millions", ascending=True)

,country,population_millions,gdp_trillions_usd,region,gdp_per_capita,gdp_per_capita_thousands
1,Germany,84,4.26,Europe,50714.285714,4.260000e-09
2,Japan,125,4.23,Asia,33840.000000,4.230000e-09
0,Brazil,214,1.92,South America,8971.962617,1.920000e-09
3,Nigeria,223,0.44,Africa,1973.094170,4.400000e-10
4,United States,333,25.46,North America,76456.456456,2.546000e-08

---
## 7. Reading Data from Files and Panel Data

In practice, you'll almost never type data in by hand. Datasets come as CSV files, Excel spreadsheets, or other formats. Pandas makes loading them straightforward.

```python
# Reading a CSV file:
df = pd.read_csv("my_data.csv")

# Reading an Excel file:
df = pd.read_excel("my_data.xlsx")
```

Both return a DataFrame, ready to work with. We'll use `pd.read_excel()` in Part II to load a real dataset.

For now, let's build a slightly larger dataset by hand that mimics the kind of **panel data** you'll see in Part II — multiple countries observed across multiple years.

In [77]:
# A small panel dataset: inflation rates for 3 countries over 4 years

panel_data = {
    "country": ["Argentina"] * 4 + ["Germany"] * 4 + ["Kenya"] * 4,
    "year": [2019, 2020, 2021, 2022] * 3,
    "inflation_pct": [
        53.5, 42.0, 48.4, 72.4,     # Argentina
        1.4,  0.4,  3.2,  8.7,      # Germany
        5.2,  5.4,  6.1,  7.6       # Kenya
    ]
}

panel = pd.DataFrame(panel_data)
panel

      country  year  inflation_pct
0   Argentina  2019           53.5
1   Argentina  2020           42.0
2   Argentina  2021           48.4
3   Argentina  2022           72.4
4     Germany  2019            1.4
5     Germany  2020            0.4
6     Germany  2021            3.2
7     Germany  2022            8.7
8       Kenya  2019            5.2
9       Kenya  2020            5.4
10      Kenya  2021            6.1
11      Kenya  2022            7.6

This structure — one row per country-year, with each variable in its own column — is called **panel data** or **long format**. It's extremely common in economics and political science. The Part II dataset follows this same pattern, just with more countries and more variables.

### Exercise 7

Add a fourth country to the panel. Create a new DataFrame called `panel_expanded` that includes all the original data plus 4 rows for a country of your choice (same years: 2019–2022) with inflation rates you make up. Display the full DataFrame.

Hint: Build a small DataFrame for just the new country, then use `pd.concat([panel, new_df], ignore_index=True)` to stack them together.

In [36]:
# Your code here
new_country = pd.DataFrame({
    "country": ["Mexico", "Mexico", "Mexico", "Mexico"],
    "year": [2019, 2020, 2021, 2022],
    "inflation_pct": [3.6, 3.4, 5.7, 7.9]
})

# Stack it onto the original panel
panel_expanded = pd.concat([panel, new_country], ignore_index=True)
panel_expanded

      country  year  inflation_pct
0   Argentina  2019           53.5
1   Argentina  2020           42.0
2   Argentina  2021           48.4
3   Argentina  2022           72.4
4     Germany  2019            1.4
5     Germany  2020            0.4
6     Germany  2021            3.2
7     Germany  2022            8.7
8       Kenya  2019            5.2
9       Kenya  2020            5.4
10      Kenya  2021            6.1
11      Kenya  2022            7.6
12     Mexico  2019            3.6
13     Mexico  2020            3.4
14     Mexico  2021            5.7
15     Mexico  2022            7.9

---
## 8. Renaming Columns

Real-world datasets often have ugly column names — long, inconsistent, full of spaces. Renaming them makes your code much easier to read and write.

In [37]:
# Imagine a dataset where a column is named something unwieldy:
ugly = panel.rename(columns={"inflation_pct": "Inflation, Annual percentages of average consumer prices"})
ugly.columns

Index(['country', 'year',
       'Inflation, Annual percentages of average consumer prices'],
      dtype='str')

In [38]:
# .rename() lets you fix it. Pass a dictionary: {old_name: new_name}
clean = ugly.rename(columns={
    "Inflation, Annual percentages of average consumer prices": "inflation"
})
clean.columns

Index(['country', 'year', 'inflation'], dtype='str')

You'll use this in Part II — the real dataset has column names that are full sentences.

### Exercise 8

The DataFrame below has two columns with clunky names. Rename them to something shorter and more usable, then display `.columns` to confirm it worked.

In [39]:
trade_data = pd.DataFrame({
    "Country or Area Name (as reported by source)": ["Mexico", "Canada", "Vietnam"],
    "Total Bilateral Trade Volume in Millions of USD (2023)": [798000, 718000, 139000]
})

# Rename the columns to something manageable, then display .columns
# Your code here

---
## 9. Handling Messy Data

Real data is messy. Numbers get stored as text, cells are empty, rows contain junk. Pandas gives you tools to deal with this.

### Converting types with `pd.to_numeric()`

In [40]:
# Sometimes numbers arrive as strings (this is common with Excel data)
messy = pd.DataFrame({
    "country": ["Chile", "Egypt", "Poland", "Somalia"],
    "inflation": ["4.5", "13.9", "N/A", "6.1"]   # note: these are strings, not numbers
})

messy.dtypes

country      str
inflation    str
dtype: object

In [41]:
# pd.to_numeric() converts a column to numbers.
# errors='coerce' turns anything it can't convert (like "N/A") into NaN
# (NaN = "Not a Number" — pandas' way of representing missing data)

messy["inflation"] = pd.to_numeric(messy["inflation"], errors="coerce")
messy

   country  inflation
0    Chile        4.5
1    Egypt       13.9
2   Poland        NaN
3  Somalia        6.1

In [42]:
# Now the dtype is float64 — a real number
messy.dtypes

country          str
inflation    float64
dtype: object

### Checking for missing values

In [43]:
# .isna() returns True where data is missing
messy["inflation"].isna()

0    False
1    False
2     True
3    False
Name: inflation, dtype: bool

In [44]:
# .notna() is the opposite — True where data exists
# This is handy for filtering out missing values
messy[messy["inflation"].notna()]

   country  inflation
0    Chile        4.5
1    Egypt       13.9
3  Somalia        6.1

### Exercise 9

The DataFrame below has a `"gdp"` column where the data arrived messy — some entries are numbers, some are text, and some are missing. Convert `"gdp"` to numeric, then filter the DataFrame to show only rows where GDP data exists (is not NaN).

In [45]:
messy_gdp = pd.DataFrame({
    "country": ["France", "India", "Peru", "Thailand", "Zambia"],
    "gdp": ["2.78", "3.39", "not reported", "0.50", ".."]
})

# Step 1: Convert the "gdp" column to numeric (coerce errors)
# Step 2: Filter to keep only rows where gdp is not NaN
# Your code here
messy_gdp["gdp"] = pd.to_numeric(messy_gdp["gdp"], errors="coerce")
messy_gdp = messy_gdp.dropna(subset=["gdp"])
messy_gdp

    country   gdp
0    France  2.78
1     India  3.39
3  Thailand  0.50

---
## 10. Using `.apply()` and Lambda Functions

Sometimes you need to apply a custom operation to every value in a column. The `.apply()` method does exactly this — it runs a function on each element (or each row) and returns the results.

A **lambda function** is just a small, anonymous function you can write inline instead of defining with `def`.

In [46]:
# Quick refresher on lambda:
# A regular function:
def double(x):
    return x * 2

# The same thing as a lambda:
double_lambda = lambda x: x * 2

print(double(5))         # 10
print(double_lambda(5))  # 10

10
10

In [78]:
# Using .apply() with a lambda on our panel data
# Let's classify each inflation observation as "high" or "normal"

if "panel" not in globals():
    panel = pd.DataFrame(panel_data) if "panel_data" in globals() else pd.DataFrame({
        "country": ["Argentina"] * 4 + ["Germany"] * 4 + ["Kenya"] * 4,
        "year": [2019, 2020, 2021, 2022] * 3,
        "inflation_pct": [53.5, 42.0, 48.4, 72.4, 1.4, 0.4, 3.2, 8.7, 5.2, 5.4, 6.1, 7.6]
    })

panel["category"] = panel["inflation_pct"].apply(lambda x: "high" if x > 10 else "normal")
panel

      country  year  inflation_pct category
0   Argentina  2019           53.5     high
1   Argentina  2020           42.0     high
2   Argentina  2021           48.4     high
3   Argentina  2022           72.4     high
4     Germany  2019            1.4   normal
5     Germany  2020            0.4   normal
6     Germany  2021            3.2   normal
7     Germany  2022            8.7   normal
8       Kenya  2019            5.2   normal
9       Kenya  2020            5.4   normal
10      Kenya  2021            6.1   normal
11      Kenya  2022            7.6   normal

You can also use `.apply()` to filter. Instead of the vectorized comparison we saw earlier (`df[df["col"] > value]`), you can write:

```python
df[df["col"].apply(lambda x: x > value)]
```

Both produce the same result. The lambda version is more flexible — you can put any logic you want inside it — but the vectorized version is faster on large datasets. Part II asks you to practice with lambda, so you'll use `.apply()` there.

In [79]:
# Filtering with lambda: same result as panel[panel["inflation_pct"] > 10]
panel[panel["inflation_pct"].apply(lambda x: x > 10)]

     country  year  inflation_pct category
0  Argentina  2019           53.5     high
1  Argentina  2020           42.0     high
2  Argentina  2021           48.4     high
3  Argentina  2022           72.4     high

### Exercise 10

Using the `panel` DataFrame and `.apply()` with a lambda:

a) Create a new column called `"severity"` that labels each row as `"crisis"` if inflation is above 40, `"elevated"` if between 5 and 40 (inclusive), and `"stable"` otherwise.

b) Filter the panel to show only the `"crisis"` rows. Which country and years appear?

In [80]:
# 10a: Your code here
panel["severity"] = panel["inflation_pct"].apply(lambda x: "crisis" if x > 40 else "normal")

In [81]:
# 10b: Your code here
panel[panel["severity"] == "crisis"]

     country  year  inflation_pct category severity
0  Argentina  2019           53.5     high   crisis
1  Argentina  2020           42.0     high   crisis
2  Argentina  2021           48.4     high   crisis
3  Argentina  2022           72.4     high   crisis

---
## 11. Grouping and Aggregating

One of the most common operations in data analysis is splitting your data into groups, computing something for each group, and combining the results. Pandas calls this **groupby**.

Example: What's the average inflation rate for each country across all years?

In [83]:
panel.groupby("country")["inflation_pct"].mean()

country
Argentina    54.075
Germany       3.425
Kenya         6.075
Name: inflation_pct, dtype: float64

That one line does a lot:
1. **Groups** the rows by country
2. **Selects** the inflation column within each group
3. **Computes** the mean for each group

You can chain `.sort_values()` to rank the results, and `.head(n)` to get the top N.

In [84]:
# Top 2 countries by average inflation
panel.groupby("country")["inflation_pct"].mean().sort_values(ascending=False).head(2)

country
Argentina    54.075
Kenya         6.075
Name: inflation_pct, dtype: float64

### Turning a grouped result back into a DataFrame

The result of `.groupby().mean()` is a **Series** (one column, indexed by the group). If you want it as a proper DataFrame with columns, use `.reset_index()`.

In [85]:
avg_inflation = panel.groupby("country")["inflation_pct"].mean().sort_values(ascending=False)

# Before reset_index — it's a Series with 'country' as the index
print(type(avg_inflation))
print(avg_inflation)
print()

<class 'pandas.Series'>
country
Argentina    54.075
Kenya         6.075
Germany       3.425
Name: inflation_pct, dtype: float64

In [86]:
# After reset_index — it's a DataFrame with 'country' as a regular column
avg_inflation_df = avg_inflation.reset_index()
print(type(avg_inflation_df))
avg_inflation_df

<class 'pandas.DataFrame'>

     country  inflation_pct
0  Argentina         54.075
1      Kenya          6.075
2    Germany          3.425

### Exercise 11

Using the `panel` DataFrame:

a) Find the **maximum** inflation rate for each country (use `.max()` instead of `.mean()`).

b) Sort the result in descending order and convert it to a DataFrame using `.reset_index()`. Round the values to 1 decimal place using `.round(1)`.

In [91]:
# Your code here
panel.groupby("country")["inflation_pct"].max()

country
Argentina    72.4
Germany       8.7
Kenya         7.6
Name: inflation_pct, dtype: float64

---
## 12. Counting Unique Values

How many distinct countries are in the dataset? How many distinct years?

In [92]:
# .unique() returns an array of distinct values
print(panel["country"].unique())

# len() counts them
print(f"Number of countries: {len(panel['country'].unique())}")

<StringArray>
['Argentina', 'Germany', 'Kenya']
Length: 3, dtype: str
Number of countries: 3

In [93]:
# .nunique() is a shortcut — it gives you the count directly
panel["year"].nunique()

4

### Exercise 12

Using the `panel` DataFrame: first, filter for rows where inflation is above 5%. Then, from that filtered result, answer: how many *unique countries* experienced inflation above 5%? How many *unique years* had at least one country above 5%?

In [94]:
# Your code here
high_inflation = panel[panel["inflation_pct"] > 5]

In [95]:
print(high_inflation["country"].nunique())  # unique countries
print(high_inflation["year"].nunique())     # unique years

3
4

---
## 13. Merging DataFrames

Sometimes the data you need lives in two separate tables and you need to join them. Pandas' `pd.merge()` works like a database join or an Excel VLOOKUP.

In [59]:
# Suppose we have a separate table of crisis indicators
crisis_data = pd.DataFrame({
    "country": ["Argentina", "Argentina", "Germany"],
    "year": [2020, 2022, 2022],
    "crisis_type": ["currency", "currency", "energy"]
})

crisis_data

     country  year crisis_type
0  Argentina  2020    currency
1  Argentina  2022    currency
2    Germany  2022      energy

In [60]:
# Merge on shared columns (country AND year)
# how="left" keeps all rows from the left DataFrame,
# filling NaN where there's no match in the right DataFrame.

merged = pd.merge(panel, crisis_data, on=["country", "year"], how="left")
merged

      country  year  inflation_pct category crisis_type
0   Argentina  2019           53.5     high         NaN
1   Argentina  2020           42.0     high    currency
2   Argentina  2021           48.4     high         NaN
3   Argentina  2022           72.4     high    currency
4     Germany  2019            1.4   normal         NaN
5     Germany  2020            0.4   normal         NaN
6     Germany  2021            3.2   normal         NaN
7     Germany  2022            8.7   normal      energy
8       Kenya  2019            5.2   normal         NaN
9       Kenya  2020            5.4   normal         NaN
10      Kenya  2021            6.1   normal         NaN
11      Kenya  2022            7.6   normal         NaN

The NaN values in `crisis_type` mean "no crisis recorded for that country-year." You could now filter for rows where a crisis occurred using `.notna()`.

In [61]:
merged[merged["crisis_type"].notna()]

     country  year  inflation_pct category crisis_type
1  Argentina  2020           42.0     high    currency
3  Argentina  2022           72.4     high    currency
7    Germany  2022            8.7   normal      energy

### Exercise 13

Below is a small DataFrame of election years. Merge it onto the `panel` DataFrame using a left join on `"country"` and `"year"`. Then filter the merged result to show only rows where an election took place. What was the inflation rate in each of those election years?

In [62]:
elections = pd.DataFrame({
    "country": ["Argentina", "Kenya", "Germany"],
    "year": [2019, 2022, 2021],
    "election_type": ["presidential", "presidential", "parliamentary"]
})

# Merge elections onto panel, then filter for rows where an election occurred
# Your code here

---
## 14. Formatting Output with `.apply()` and Lambda

When you're presenting results, raw floats aren't always readable. You can use `.apply()` with a lambda to format numbers as strings.

In [63]:
# Round and format inflation as a percentage string
panel["inflation_display"] = panel["inflation_pct"].apply(lambda x: f"{x:,.1f}%")
panel[["country", "year", "inflation_display"]]

      country  year inflation_display
0   Argentina  2019             53.5%
1   Argentina  2020             42.0%
2   Argentina  2021             48.4%
3   Argentina  2022             72.4%
4     Germany  2019              1.4%
5     Germany  2020              0.4%
6     Germany  2021              3.2%
7     Germany  2022              8.7%
8       Kenya  2019              5.2%
9       Kenya  2020              5.4%
10      Kenya  2021              6.1%
11      Kenya  2022              7.6%

### Exercise 14

Using the `df` DataFrame (our original 5-country dataset), create a new column called `"gdp_display"` that formats `"gdp_trillions_usd"` as a dollar string — for example, `"$4.26T"`. Use `.apply()` with a lambda. Display just the `"country"` and `"gdp_display"` columns.

In [64]:
# Your code here

---
## 15. Using `.filter()` to Select Columns

If you only want certain columns and don't want to type all the bracket notation, `.filter()` is a convenient shorthand.

In [65]:
# Equivalent to panel[["country", "year", "inflation_pct"]]
panel.filter(["country", "year", "inflation_pct"])

      country  year  inflation_pct
0   Argentina  2019           53.5
1   Argentina  2020           42.0
2   Argentina  2021           48.4
3   Argentina  2022           72.4
4     Germany  2019            1.4
5     Germany  2020            0.4
6     Germany  2021            3.2
7     Germany  2022            8.7
8       Kenya  2019            5.2
9       Kenya  2020            5.4
10      Kenya  2021            6.1
11      Kenya  2022            7.6

---
## Putting It All Together

Let's walk through a mini-analysis that chains several of these operations — the same pattern you'll follow in Part II.

**Question:** Which countries experienced inflation above 30%, and what was their average rate in those high-inflation years?

In [66]:
# Start from the panel DataFrame
# Step 1: Filter for inflation above 30%
high_infl = panel[panel["inflation_pct"].apply(lambda x: x > 30)]

# Step 2: How many countries?
print(f"Countries with >30% inflation: {len(high_infl['country'].unique())}")

# Step 3: Average inflation in those episodes
avg_by_country = high_infl.groupby("country")["inflation_pct"].mean().reset_index()
avg_by_country["inflation_pct"] = avg_by_country["inflation_pct"].apply(lambda x: round(x, 2))
avg_by_country

Countries with >30% inflation: 1

     country  inflation_pct
0  Argentina          54.08

### Exercise 15 (Challenge)

This one combines everything. Using the `panel` DataFrame:

1. Rename `"inflation_pct"` to `"inflation"`
2. Filter for inflation above 6% using `.apply()` with a lambda
3. Select only the `"country"`, `"year"`, and `"inflation"` columns using `.filter()`
4. Round the inflation values to 1 decimal place using `.apply()` with a lambda
5. Find the top 2 countries by average inflation (using `.groupby()`, `.mean()`, `.sort_values()`, `.head()`)
6. Convert the result to a DataFrame with `.reset_index()`

In [67]:
# Your code here — try to do it step by step, one operation at a time.
# You can use multiple cells if you want to check your work as you go.

---

## Quick Reference

| What you want to do | Code |
|---|---|
| Load a CSV | `pd.read_csv("file.csv")` |
| Load an Excel file | `pd.read_excel("file.xlsx")` |
| See dimensions | `df.shape` |
| See column names | `df.columns` |
| See data types | `df.dtypes` |
| First N rows | `df.head(n)` |
| Summary stats | `df.describe()` |
| Select one column | `df["col"]` |
| Select multiple columns | `df[["col1", "col2"]]` |
| Filter rows | `df[df["col"] > value]` |
| Filter with lambda | `df[df["col"].apply(lambda x: x > value)]` |
| Rename columns | `df.rename(columns={"old": "new"})` |
| Sort | `df.sort_values("col", ascending=False)` |
| Group and aggregate | `df.groupby("col")["val"].mean()` |
| Count unique values | `len(df["col"].unique())` or `df["col"].nunique()` |
| Convert to numeric | `pd.to_numeric(df["col"], errors="coerce")` |
| Check for missing data | `df["col"].isna()` / `df["col"].notna()` |
| Merge two DataFrames | `pd.merge(df1, df2, on="col")` |
| Series to DataFrame | `series.reset_index()` |

---
---
# Part II: Global Financial Crises Dataset

Below is a link to data collected over many years by Carmen Reinhart (with her coauthors Ken Rogoff, Christoph Trebesch, and Vincent Reinhart). These include Banking Crisis dates for more than 70 countries from 1800-present, exchange rate crises, stock market crises, sovereign debt growth and default, and many other data series.
Please download here:

https://www.hbs.edu/behavioral-finance-and-financial-stability/data/Pages/global.aspx

For the following, please show me that you know how to use lambda and map functions where possible and efficient.

Q1: Read the data from the excel file into a pandas data frame:

In [68]:
# Your code here

Q2. From the dataset, create a new dataframe. Using a lambda function, select only those incidents where the annual inflation rate was 25% or higher. The dataframe should have three columns, Country Name, Year and Inflation rate.

In [69]:
# Your code here

Q3. Write code to tell me how many countries experienced 25% inflation or higher?

In [70]:
# Your code here

Q4. How many years across all countries were there events of 25% or higher inflation?

In [71]:
# Your code here

Q5. Of the years where inflation was 25% or higher, how many of those years resulted in a systemic crisis?

In [72]:
# Your code here

Q6. What were the countries and years associated with the total from Q5?

In [73]:
# Your code here

Q7. At times of civil unrest or war, what was the average interest rate?

In [74]:
# Your code here

Q8: Create a new dataframe that lists the top five countries with the average highest interest rates historically, with a column for the country, and the average rate.

In [75]:
# Your code here

Q9: Create a new dataframe that lists the countries and years where there was "negative inflation".
What does negative inflation mean, and why did it occur?

In [76]:
# Your code here

Your explanation here: